### ISSUE TITLE
t2 init missing .npmrc

### ISSUE THREAD

**Issue by ptauk** [tessel/t2-cli#1284]
I have recently updated to 0.1.7 of t2-cli and encountered the issue when I try to run a program I get the following error:
`
WARN This project is missing an ".npmrc" file!`
`WARN To prepare your project for deployment, use the command:`
`WARN`
`WARN t2 init`
`WARN`
`WARN Once complete, retry:`
`WARN`
`WARN t2 run server.js
`
I try to rerun t2 init and I get:
...
`INFO Created ".npmrc".`
...

Running the program again using t2 run server.js causes the same error.
What might be going on here? Thanks

**Comment by rwaldron** [comment]
Can you provide details about the environment you're working in? OS, node version, npm version, etc. Would you mind trying the Smoke Tests described here: https://github.com/tessel/t2-cli/pull/1267

Thanks!

**Comment by rwaldron** [comment]
Duplicate of #1276

**Comment by boneskull** [comment]
@ptauk this is fixed in v0.1.8 of `t2-cli`

**Comment by soapdog** [comment]
@boneskull it is still happening for with with v0.1.8 on Windows 10.

![cmder 2017-07-24 16 10 23](https://user-images.githubusercontent.com/23247/28540222-e245026a-708a-11e7-9f47-b8c1f1948ff5.png)

**Comment by rwaldron** [comment]
Did the reply get deleted? Can this be closed?

**Comment by soapdog** [comment]
@rwaldron the reply was mine, I posted before doing more tests and found the error to be on my side, so I deleted the useless reply (it was only here for some minutes). Sorry for the confusion

**Comment by rwaldron** [comment]
Ok, no problem :D

**Comment by rwaldron** [comment]
Sorry, can this be closed?

**Comment by ptauk** [comment]
Sorry for the delay, this can be closed it was fixed by upgrading to v0.1.8 of t2-cli.

**Comment by rwaldron** [comment]
@ptauk thank you for the follow up ❤️
